import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

import {
  DARK_BRAND_ALGORITHM_VERSION,
  MUSUBI_BRAND_SEED,
  MUSUBI_DARK_ACCENT_BACKGROUNDS,
  deriveDarkBrandColor,
} from './lib/dark-brand-color.ts'

const outputUrl = new URL('../app/assets/css/brand.generated.css', import.meta.url)

function renderGeneratedCss(): string {
  const darkBrandColor = deriveDarkBrandColor(MUSUBI_BRAND_SEED)
  return `/*
 * Generated by \`vp run brand:update\`. Do not edit by hand.
 * Dark brand algorithm: v${DARK_BRAND_ALGORITHM_VERSION}
 * Checked accent backgrounds: ${MUSUBI_DARK_ACCENT_BACKGROUNDS.join(', ')}
 */
:root {
  --brand-accent-light: ${MUSUBI_BRAND_SEED.toLowerCase()};
  --brand-accent-dark: ${darkBrandColor.toLowerCase()};
}`
}

const shouldWrite = process.argv.includes('--write')
const shouldCheck = process.argv.includes('--check')
if (shouldWrite === shouldCheck) {
  throw new Error('Pass exactly one of --write or --check')
}

const expected = renderGeneratedCss()
if (shouldWrite) {
  await writeFile(outputUrl, expected, 'utf8')
  console.log(`Updated ${fileURLToPath(outputUrl)}`)
} else {
  const actual = await readFile(outputUrl, 'utf8').catch(() => '')
  if (actual !== expected) {
    throw new Error(
      'Generated brand colors are stale. Run `vp run brand:update` and commit the result.',
    )
  }
  console.log('Generated brand colors are current.')
}